Deunwrap extract_function
rust-lang/rust-analyzer pull request #15431
Opened 2023-08-09 23:01 UTC by alibektas

#15398 subtask 5.

2023-08-15 07:08 UTC, Veykril requested changes
Also a pretty expensive assist, so we should make sure this stays lazy

2023-08-15 07:08 UTC, Veykril commented on crates/ide-assists/src/handlers/extract_function.rs
> +                    ted::replace(node.syntax(), node.expr()?.syntax());
Let's turn these into `if let`s and do nothing for the `None` case.

2023-08-15 07:08 UTC, Veykril commented on crates/ide-assists/src/handlers/extract_function.rs
> +            let expr = ast::Expr::cast(expr)?;
Can't happen, so let's make this an expect

2023-08-18 13:50 UTC, alibektas commented
@rustbot review

2023-09-08 11:00 UTC, Veykril requested changes

2023-09-08 11:00 UTC, Veykril commented on crates/ide-assists/src/handlers/extract_function.rs
> +
Given the other reviews, all of this can stay in the builder closure

2023-09-10 21:05 UTC, alibektas commented
It seems like I did more damage than fixing stuff with these last commits :smile:. So now I basically took the original version ( without actually reverting it) and changed `unwrap`s to `expect`s

2023-09-11 08:23 UTC, Veykril approved these changes

2023-09-11 08:23 UTC, Veykril commented
@bors r+

2023-09-11 08:53 UTC, merged