Add config option to use `rust-analyzer` specific target dir
rust-lang/rust-analyzer pull request #15681
Opened 2023-09-29 08:52 UTC by Tyrubias

Adds a Rust Analyzer configuration option to set a custom target directory for builds. This is a workaround for Rust Analyzer blocking debug builds while running `cargo check`. This change should close #6007

2023-09-29 10:08 UTC, Veykril requested changes

2023-09-29 10:08 UTC, Veykril commented on crates/rust-analyzer/src/config.rs
> +    Directory(String),
```suggestion
    Directory(PathBuf),
```

2023-09-29 10:08 UTC, Veykril commented on crates/rust-analyzer/src/config.rs
> +                add_target_dir_to_args(&mut extra_args, target_directory);
We should add a dedicated field to `FlyCheckConfig` instead

2023-09-29 10:08 UTC, Veykril commented on crates/rust-analyzer/src/config.rs
> +        add_target_dir_to_args(&mut extra_args, target_directory);
We should add a dedicated field for this to `CargoConfig` instead

2023-10-01 01:35 UTC, Tyrubias commented
@Veykril I realized it might not make sense for us to pass `--target-dir` to a Flycheck custom command. Should we set `CARGO_TARGET_DIR` for Flycheck custom commands?

2023-10-01 05:28 UTC, Veykril commented
Why would the env var make more sense then passing the flag?

2023-10-01 05:43 UTC, Tyrubias commented
Is it not possible for the Flycheck custom command to invoke another command that invokes `cargo`? In that case adding `--target-dir` would cause an error, but then the environment variable might eventually be inherited by the `cargo` process. Please let me know if I'm mistaken.

2023-10-04 11:57 UTC, Veykril commented
That's fine, if you use a command override most of the settings no longer apply. In general we expect people to completely build up their command if they use an override.

2023-10-04 13:14 UTC, Tyrubias commented
That makes sense, I've changed it back to using `--target-dir` instead of `CARGO_TARGET_DIR`. Are there any more tests I should add for this behavior? Thanks.

2023-10-09 06:39 UTC, Veykril commented on crates/flycheck/src/lib.rs
> +        target_dir: Option<PathBuf>,
```suggestion
```

If the user uses a custom command they should be specifying the target dir themselves in the args as we can't predict what format their command expect.

This is the bahvior with all cargo config args, we drop them all for the custom command

2023-10-09 06:39 UTC, Veykril commented on crates/rust-analyzer/src/config.rs
> +            .flatten()
```suggestion
            .and_then(|target_dir| match target_dir {
                TargetDirectory::UseSubdirectory(true) => {
                    Some(PathBuf::from("target/rust-analyzer"))
                }
                TargetDirectory::UseSubdirectory(false) => None,
                TargetDirectory::Directory(dir) => Some(dir.clone()),
            })
```

2023-10-09 06:39 UTC, Veykril commented on crates/rust-analyzer/src/config.rs
> +        /// This is useful to prevent rust-analyzer's `cargo check` from blocking builds.
```suggestion
        /// This is prevents rust-analyzer's `cargo check` from locking the `Cargo.lock` at the expense of duplicating build artifacts.
```

2023-10-09 07:16 UTC, Tyrubias commented
Thank you so much for the mentorship! I've addressed your comments.

@rustbot ready

2023-10-09 07:25 UTC, Veykril approved these changes

2023-10-09 07:25 UTC, Veykril commented
Thanks!
@bors r+

2023-10-09 07:44 UTC, merged

2023-10-16 07:46 UTC, lnicola commented on crates/rust-analyzer/src/config.rs
> +        rust_analyzerTargetDir: Option<TargetDirectory> = "null",
Would have made sense to call this `cargo_` instead.

2023-10-16 09:27 UTC, matklad commented
Brilliant idea!