fix: `extract_struct_from_enum_variant` assist should resolve Self generic arg
rust-lang/rust-analyzer pull request #16199
Opened 2023-12-26 13:30 UTC by Young-Flash

close https://github.com/rust-lang/rust-analyzer/issues/16197

2023-12-27 11:58 UTC, Young-Flash commented
sorry I miss the case that nested generic arg with `Self`, corrected now.

it's ready for review.

2024-01-02 15:46 UTC, Veykril requested changes

2024-01-02 15:46 UTC, Veykril commented on crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
> +                .count();
This should use the `PathTransform::transform_path` function to transform the `Self` path

2024-01-04 15:32 UTC, Young-Flash commented
@rustbot ready

2024-01-05 13:14 UTC, Veykril approved these changes

2024-01-05 13:14 UTC, Veykril commented
Thanks!
@bors r+

2024-01-05 13:36 UTC, merged