fix: Goto implementation to impls inside blocks
rust-lang/rust-analyzer pull request #16812
Opened 2024-03-11 16:13 UTC by ShoyuVanilla

Fixes #3739

2024-03-11 16:18 UTC, ShoyuVanilla commented on crates/hir-ty/src/method_resolution.rs
>              }
The logic is quite verbose, but I couldn't find any good ways that can probe into those blocks 🤔

2024-03-12 09:58 UTC, Veykril requested changes
We intentionally do not look into all blocks there are, as an IDE we try to be lazy and only analyze the crate structure on a global scale, which allows us to skip out on having to look into every body which would slow us down immensely. So supporting local impls like this isn't really possible. 

So what we should do instead to make the first case work is have `goto_implementation` look into the block defmaps of the ADT/trait definition and iterate those. We can query the relevant impls via the `*_impls_in_block` queries (check for uses of those queries, that should show you how to use thisI think, if not just ask)

2024-03-12 09:58 UTC, Veykril commented on crates/ide/src/goto_implementation.rs
> +    fn goto_implementation_in_nested_blocks_2() {
This test we cannot support due to performance reasons, see the main review message

2024-03-12 09:58 UTC, Veykril commented on crates/ide/src/goto_implementation.rs
> +    fn goto_implementation_in_nested_blocks_1() {
This we can support

2024-03-15 18:34 UTC, ShoyuVanilla commented
I'm seeking some performant implementation; is there any way to find `BlockId` with current cursor location? 🤔

2024-03-15 21:41 UTC, Veykril commented
You can turn block expression ast nodes into blocks via https://github.com/rust-lang/rust-analyzer/blob/0dd89d7ee7800c53dc10cec941c4e740562d54df/crates/hir/src/semantics/source_to_def.rs#L205 (Note that will only yield `Some` for blocks that actually have local items or macro calls in them due to perf optimizations)

2024-03-16 02:42 UTC, ShoyuVanilla commented
Thank you! I'll look into that point 😄

2024-03-19 13:14 UTC, Veykril commented
Thanks!
@bors r+

2024-03-19 13:27 UTC, merged