Wait for discover command on Finished/Error
rust-lang/rust-analyzer pull request #18280
Opened 2024-10-10 17:44 UTC by darichey

Currently, we [kill](https://github.com/rust-lang/rust-analyzer/blob/0fb804acb375b02a3beeaceeb75b71969ef37b15/crates/rust-analyzer/src/command.rs#L92) the discover process upon receiving Finished/Error which prevents it from completing gracefully and doing any cleanup/logging ([as we want to do in rust-project](https://github.com/facebook/buck2/blob/66be61717ff358cd9a4da4acd2acffc2f52d7052/integrations/rust-project/src/cli/develop.rs#L222)). Wait for it to exit instead.

2024-10-10 19:11 UTC, davidbarsky requested changes
`homer_bushes.gif`

(lgtm modulo suggested nits.)

2024-10-10 19:11 UTC, davidbarsky commented on crates/rust-analyzer/src/main_loop.rs
> +                let discover_handle = self.discover_handle.take().unwrap();
```suggestion
                let discover_handle = self.discover_handle.take().expect("no project discovery command set; this is a bug.");
```

2024-10-10 19:11 UTC, davidbarsky commented on crates/rust-analyzer/src/main_loop.rs
> +                let discover_handle = self.discover_handle.take().unwrap();
```suggestion
                let discover_handle = self.discover_handle.take().expect("no project discovery command set; this is a bug.");
```

2024-10-14 11:04 UTC, Veykril reviewed
That does mean the main loop will block on the process exiting which I don't think is a good idea?

2024-10-14 19:33 UTC, darichey commented
Closing in favor of https://github.com/facebook/buck2/commit/ae1b8e4bda7e3ebddd2cd628a775d8be81de3bcc

2024-10-14 19:33 UTC, closed without merging