Re-add `rust-analyzer.cargo.sysrootQueryMetadata`
rust-lang/rust-analyzer pull request #18511
Opened 2024-11-14 18:37 UTC by darichey

#17795 removed this option, turning it on for everyone. This commit adds it back, still on by default.

At work, users are effectively offline, so the initial `cargo metadata` will always fail. The `--no-deps` retry will succeed, but the experience with this path is very poor, because a ton of std stuff fails to resolve (some still works, I can't tell the pattern).
<img width="397" alt="Screenshot 2024-11-14 at 12 32 23 PM" src="https://github.com/user-attachments/assets/a1398b85-9937-4e72-a492-3f34fc501c15">

We want this config option so we can turn it off by default for our users and always use the stitched sysroot library.

2024-11-14 18:38 UTC, darichey commented
> The `--no-deps` retry will succeed, but the experience with this path is very poor, because a ton of std stuff fails to resolve

In fact, this experience is so poor, I wonder if it's even worth supporting?

2024-11-14 18:40 UTC, darichey commented
If we'd like to get rid of the stitched sysroot stuff, a longer term solution could be teaching rust-analyzer to use something other than `cargo metadata` for this. At work, the sysroot builds with Buck, so presumably we could use it to get the info we need.

2024-11-15 15:19 UTC, davidbarsky requested changes
I'm a plus one on this, but I'd prefer someone

2024-11-19 17:05 UTC, lnicola approved these changes

2024-11-26 05:36 UTC, lnicola commented
r? @davidbarsky

2024-11-26 15:14 UTC, davidbarsky commented
> I know, but I wasn't able to merge it because of your pending "changes requested" review.

Wild, okay! I thought it was overridable.

2024-11-26 15:17 UTC, lnicola commented
I know, check out my struggles in the history above 😕.

2024-11-26 15:18 UTC, davidbarsky commented
> I know, check out my struggles in the history above 😕.

I didn't see those in email and I didn't stroll up. I'm sorry about that.

2024-11-26 15:26 UTC, merged

2024-12-02 12:08 UTC, Veykril commented
> At work, users are effectively offline, so the initial `cargo metadata` will always fail. The `--no-deps` retry will succeed, but the experience with this path is very poor, because a ton of std stuff fails to resolve (some still works, I can't tell the pattern). 

Hmm, that seems very odd to me? The no-deps retry should yield the same result as the stitched workspace

2024-12-02 12:15 UTC, Veykril commented
In fact, I can't reproduce this. If I run r-a offline I still get resolved standard library stuff. I'd really prefer to get rid of this config as I'd like to drop the stitched workspace hack in the near future